### ISSUE TITLE
Benchmarking for pdf in PETSc library.

### ISSUE THREAD

**Issue by AjaySingh40** [qsnake/petsc#1]
1)  I  want to benchmark petsc library. I don't find any parameter to be changed like size of matrix/vector etc. as in the case of blas or lapack. I can see the N and M used in  examples under matrix  / vector types in petsc but they are internally allocating the sizes. How can we change values of those variables .
2)  Is there any website or tutorials available for petsc benchmarking which have small programs with one or two routines of petsc.
3)  Out of the three methods Finite Element, finite difference and finited volume methods which method is best for benchmarking.
4)  Out of all these Application Codes TS, PC, KSP, matrices and Vectors which one is best for linear.
Thank You.

**Comment by certik** [comment]
The main development repository of PETSc is at https://gitlab.com/petsc/petsc, so you should ask there.
